#!/bin/sh

# E-mail, subdomain and people names harvester
# https://github.com/laramies/theHarvester
# e.g. `harvest -d cerberus.com -b all`

docker run theharvester $@

# if `WORDLISTS_DIR` is unset, use `HARVESTER_WORDLISTS_DIR`
# as harvester's wordlists dir
if [ -z "$WORDLISTS_DIR" ]; then
    WORDLISTS_DIR=$HARVESTER_WORDLISTS_DIR
fi
WORDLISTS_DIR=$WORDLISTS_DIR python3 $PYTHON_HARVESTER_PATH $@
