#!/bin/sh

file=$@
[ -z "$file" ] && echo "Usage: $(basename $0) some-video.mov" && exit 0

# Don't do anything if file is not .mp4 or .mov
[ -z $(echo "$file" | grep -E '(.mp4|.mov)$') ] && exit 0

# Show error if makemp4 is missing
hash makemp4 2>/dev/null || { osascript -e "display dialog \"Could not convert to .mp4: 'makemp4' is missing\"" && exit 1; }

echo "Optimizing video.."
makemp4 "$file"

echo "Deleting original file.."
trash "$file"
