#!/bin/bash

if [ "$1" = "-h" ]; then
  echo "$(basename $0) – create markdown note for PR review note."
  echo "The output will be stored in the same directory of input file."
  echo "Usage: $(basename $0)"
  echo "Example: $(basename $0)"
  exit
fi

if [ ! -d "./.work" ]; then
  echo "Creating workspace directory (one time only)..."
  mkdir ./.work
fi

branchname=$(git branch --show-current)
branchname_no_suffix=$(echo $branchname | sed 's#wzulfikar/##')
filepath="./.work/$(date -I)-review_$branchname_no_suffix.md"

# Get name of branch creator based on last commit
author_name="$(git log -n1 --pretty=format:"%an (%ae)")"

# Get PR URL
pr_url=$(gh pr view --json url | jq -r '.url')

if [ -f "$filepath" ]; then
  echo "File already exists: $filepath"
  exit
fi

touch $filepath

#region Create template string
TEMPLATE="Slack/Notion: here
Branch: $branchname
Author: $author_name
PR: [here]($pr_url)

---

## Steps to review:

- Gather info to understand the context:

  - [ ] Read task description in Notion/Slack
  - [ ] Read PR description

- Self check:

  - [ ] What's the business requirement of this PR?

- Implementation details:

  - [ ] Check the code changes
  - [ ] Check if specs are updated
  - [ ] Run the flow locally
  - [ ] Add comments/questions in the PR (if any)

## Notes

"
#endregion

echo "File created: $filepath"
echo "$TEMPLATE" > $filepath
code $filepath

echo "Tip: Press cmd+k,shift+enter to pin the file in VSCode."
