#!/bin/sh

# video to convert to gif
input_file=$1
output_file="$1.gif"

fps_default=8
scale_default=720

scale=${2:-${scale_default}}
fps=${3:-${fps_default}}

if [ -z "$1" ] || [ "$1" = "-h" ]; then
	echo "$(basename $0) – converts given video file to GIF using ffmpeg."
	echo "The output will be stored in the same directory of video file."
	echo "Usage: $(basename $0) <video file> [scale] [fps]"
	echo "Examples:"
	echo "- convert video to GIF of default scale ($fps_default) & fps ($scale_default):"
	echo "  $(basename $0) my-video.mp4"
	echo "- specify custom scale & fps:"
	echo "  $(basename $0) my-video.mp4 320 24"
	exit
fi

hash ffmpeg 2>/dev/null || { echo "ERROR: missing dependencies: 'ffmpeg'" && exit 1; } # check dependencies

# Check extension and skip if not mov/mp4/mkv
ext=$(echo "${input_file##*.}" | tr '[:upper:]' '[:lower:]')
if [ "$ext" != "mov" ] && [ "$ext" != "mp4" ] && [ "$ext" != "mkv" ]; then
  echo "[ERROR] extension must be .mov, .mp4, or .mkv"
  exit
fi

echo "[INFO] making gif.."
echo "output file: $output_file"

if [ "$scale" = "$scale_default" ]; then
	echo "scale: ${scale} (default)"
else
	echo "scale: ${scale}"
fi

if [ "$fps" = "$fps_default" ]; then
	echo "fps: ${fps} (default)"
else
	echo "fps: ${fps}"
fi

echo ""

# adopted from http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html
palette="/tmp/palette.png"
filters="fps=${fps},scale=${scale}:-1:flags=lanczos"

# create palette
ffmpeg \
	-i "$input_file" \
	-loglevel panic -hide_banner -nostats \
	-vf "$filters,palettegen" \
	-y "$palette"

# create gif
ffmpeg \
	-i "$input_file" \
	-loglevel panic -hide_banner -nostats \
	-i $palette \
	-lavfi "$filters [x]; [x][1:v] paletteuse" \
	-y "$output_file"
