#!/bin/sh

# See .env

# .aliases
[ -z "$GIST_ID_ALIASES" ] && echo "ERROR: Missing env var 'GIST_ID_ALIASES'" && exit 1
echo "- Updating gist for ~/.aliases"
gh gist edit ${GIST_ID_ALIASES} -f .aliases ~/.aliases
echo "  Done! https://gist.github.com/${GIST_ID_ALIASES}"

# .zshrc
[ -z "$GIST_ID_ZSHRC" ] && echo "ERROR: Missing env var 'GIST_ID_ZSHRC'" && exit 1
echo "- Updating gist for ~/.zshrc"
gh gist edit ${GIST_ID_ZSHRC} -f .zshrc ~/.zshrc
echo "  Done! https://gist.github.com/${GIST_ID_ZSHRC}"

# .nanorc
[ -z "$GIST_ID_NANORC" ] && echo "ERROR: Missing env var 'GIST_ID_NANORC'" && exit 1
echo "- Updating gist for ~/.nanorc"
gh gist edit ${GIST_ID_NANORC} -f .nanorc ~/.nanorc
echo "  Done! https://gist.github.com/${GIST_ID_NANORC}"

# zed configs
echo "- Updating gist for zed: keymap.json, settings.json, tasks.json, snippets/snippets.json, snippets/typescript.json"
gh gist edit ${GIST_ID_ZED} -f keymap.jsonc ~/.config/zed/keymap.json
gh gist edit ${GIST_ID_ZED} -f tasks.jsonc ~/.config/zed/tasks.json
gh gist edit ${GIST_ID_ZED} -f snippets_snippets.jsonc ~/.config/zed/snippets/snippets.json
gh gist edit ${GIST_ID_ZED} -f snippets_typescript.jsonc ~/.config/zed/snippets/typescript.json
echo "  Done! https://gist.github.com/${GIST_ID_ZED}"
